# Generated by Django 3.1.3 on 2020-11-28 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdentificationDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default=' ', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MaritalStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default=' ', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default=' ', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=256)),
                ('first_last_name', models.CharField(max_length=256)),
                ('second_last_name', models.CharField(max_length=256)),
                ('number_identification', models.CharField(max_length=256)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(max_length=256)),
                ('residence_address', models.CharField(max_length=256)),
                ('main_phone', models.CharField(max_length=256)),
                ('secondary_phone', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=256)),
                ('identification_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.identificationdocument')),
                ('marital_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.maritalstatus')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.study')),
            ],
        ),
    ]
