# Generated by Django 3.1.3 on 2020-11-28 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study',
            name='name',
        ),
        migrations.AddField(
            model_name='study',
            name='year_in_school',
            field=models.CharField(choices=[('NO', 'Sin estudios'), ('BA', 'Primaria/bachillerato'), ('PR', 'Profesional/técnico/tecnólogo'), ('PO', 'Posgrado')], default=' ', max_length=2),
        ),
    ]
