# Generated by Django 3.1.3 on 2020-11-28 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20201128_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study',
            name='year_in_school',
        ),
        migrations.AddField(
            model_name='study',
            name='name',
            field=models.TextField(default=' ', max_length=200),
        ),
    ]
